hwdec=auto-safe
keep-open=no
loop-playlist=inf
save-position-on-quit=no
osc=yes
border=no
alang=jpn,kor,eng
slang=eng
profile=gpu-hq
autofit=1080x960
keepaspect-window=no
geometry=1080x960
volume=50
af=lavfi=[dynaudnorm=f=150:g=15:p=0.9]
sid=no
sub-auto=no
